name: Python application

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up tox for Python 3.8
      uses: actions/setup-python@v1
      with:
        workdir: 'page-objects'
        python-version: 3.8
        run: |
          python -m pip install --upgrade pip
          pip install tox
          tox